### PR TITLE
Use the original repo

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
I created this PR so that I could ask you (@bpmn-io) to enable issues on this GH repo.

**Comment by graingert** [comment]
Maybe we can all agree on a single repo/npm name https://github.com/gabelerner/canvg/pull/477

**Comment by nikku** [comment]
Closing due to inactivity.

**Comment by graingert** [comment]
@nikku the activity was in this issue: https://github.com/canvg/canvg/pull/477

**Comment by nikku** [comment]
I meant interactivity from our side.

Cf. my last comment (three years old): https://github.com/camunda/camunda-modeler/issues/423#issuecomment-267077642

**Pull request closed without merging**
